[package]
name = "axum-staticfile-logger-query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "^0.7"
serde = { version = "1.0.193", features = ["derive"] }
tokio = { version = "1.28.2", features = ["full"] }
tower-http = { version = "^0.5", features = ["fs", "trace"] }
tracing = "^0.1.40"
tracing-subscriber = "^0.3.18"
